# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvqwNybPHPkjIInkqM5uqBEKFzB--82A
"""

import streamlit as st
import pandas as pd
st.set_page_config(page_title="Iris Dashboard App", layout="centered")
st.write("This is simple streamlit app deployed from github.")

st.sidebar.header("Dashboard")
